version: '3.9'

services:
  db:
    image: neo4j
    restart: unless-stopped
    stop_grace_period: 1m30s
    volumes:
      - top-data:/data
    env_file:
      - docker-compose.env

  backend:
    image: ghcr.io/onto-med/top-backend
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - docker-compose.env
    environment:
      - APP_PATH=/api
      - DB_HOST=db
      - DB_PORT=7687

  frontend:
    image: ghcr.io/onto-med/top-frontend
    restart: unless-stopped
    depends_on:
      - backend
    env_file:
      - docker-compose.env

  caddy:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
    env_file:
      - docker-compose.env

volumes:
  top-data:
  caddy-data:
